### ISSUE TITLE
Document pass-through behavior

### ISSUE THREAD

**Issue by kylecordes** [joliss/broccoli-coffee#5]
This plug-in appears to pass through all non-coffee files as is, while swapping out coffee files to JavaScript files. I found that surprising, and ended up chaining  on another plug-in to strip out all but the JavaScript files.

Is the right idiom that a Broccoli build process should pass essentially all files through a series of plug-ins, each of which transparently passes along everything it doesn't care about? Or is the right idiom that one should use a bunch of plug-ins to process different kinds of things, then merge together the results in at the end? Maybe the former seems more suitable if most plug-ins will make a one to one file mapping? Maybe the latter seems more suitable if most plug-ins will return a tree of substantially different shape than what they accept?

I don't know the answer to the idiom question; but I do know this:

It would be easier to understand while getting started, if plug-ins would state in their documentation what they do with files they don't care about.

If you would rather have a pull request than this wall of text, just say so :-)

**Comment by joliss** [comment]
Over 3 years later, fixed in 4e00d5b! :-)
